### ISSUE TITLE
The MQTT source connector does not reconnect when first connect call fails

### ISSUE THREAD

**Issue by NiekPeeters** [lensesio/stream-reactor#424] opened 2018-04-10 13:38 UTC
When the first attempt to connect to the mqtt broker fails, the task enters the failed state and will never reconnect.
As a result, the task needs to be manually restarted. The task should attempt automatic reconnect just like normal.

**Comment by Antwnis** [comment] 2018-04-25 12:37
Hi @NiekPeeters 

Is your PR #425 now resolving this ticket or is this about another issue ?

**Comment by NiekPeeters** [comment] 2018-04-25 12:43
This is another ticket and not fixed. At first I thought I had to implement the entire reconnecting logic myself so fixing this ticket could directly be picked up by the same PR, but it turned out that implementing the entire reconnecting logic wasn't necessary. I still think this issue should be picked up soon.

**Comment by ryan2x** [comment] 2018-05-18 06:34
Hey, @NiekPeeters 
For MQTT Paho (org.eclipse.paho.client.mqttv3), the current code is using synchronized calls, that is not meant for production. The implementation shall use the asynchronous Paho API instead. I used the MQTT Sink/Source, and the connector will crash after about 1-2 days of running. In the mean time, I have another Java code using the asynchronous API, handling massive messages (more than 1000 messages per second), and works for months without any problem. Hope you guys can fix that. Or when I got a bit time later, I can contribute to fix this bug as well. For now, I have to abandon the MQTT sink/source due to unstable connection, although I got everything else working.

**Comment by andrewstevenson** [comment] 2018-05-18 07:14
@ryan2x contributions welcome!

**Comment by stheppi** [comment] 2018-05-18 07:45
@ryan2x is there a note in the documentation asking not to use the provided API? (https://www.eclipse.org/paho/files/mqttdoc/MQTTClient/html/async.html} . Pretty unusual for a Framework  to provide an API with  a note - do not usr it gor production.Forasync will scale better on larger volumes,but in performance and stability are two different things. It is one thing to handle 500 msg a second or 1000, but in both cases the framework should be stable.

Do you mind sharing the crash stack, maybe there is there something pointing to the underlying issue.

**Comment by andrewstevenson** [comment] 2020-04-29 11:35
closing due to inactivity and not reproducible

**Closed by andrewstevenson** 2020-04-29 11:35 UTC
