### ISSUE TITLE
"Primary key column id is not set" while trying to push data from kafka topics to kudu table.

### ISSUE THREAD

**Issue by mohanrajank** [lensesio/stream-reactor#638] opened 2020-01-03 11:09 UTC
# Issue Guidelines
trying to push the data from kafka-topic to kudu table in cloudera using this connector kafka-connect-kudu-1.2.3-2.1.0-all.jar, 
1. **Created the kudu table using this steps:**
impala-shell -d default
CREATE TABLE IF NOT EXISTS date_test(
id integer primary key,
msg string,
created_at timestamp
)
PARTITION BY HASH PARTITIONS 3
STORED AS KUDU;

2. **Sink connector config**
{
  "name": "snk_test",
    "config": {
    "connector.class": "com.datamountaineer.streamreactor.connect.kudu.sink.KuduSinkConnector",
    "topics": "mssql.dbo.date_test",
    "connect.kudu.schema.registry.url": "http://localhost:8081",
    "connect.kudu.master": "kudumaster:7051",
    "connect.kudu.kcql": "insert into impala::default.date_test select * from mssql.dbo.date_test"
  }
}
3. **Error log**
Caused by: java.lang.RuntimeException: org.apache.kudu.client.NonRecoverableException: Primary key column id is not set\n\tat com.datamountaineer.streamreactor.connect.errors.ThrowErrorPolicy.handle
Please review these questions before submitting any issue?

### What version of the Stream Reactor are you reporting this issue for?
kafka-connect-kudu-1.2.3-2.1.0-all.jar
### Are you running the correct version of Kafka/Confluent for the Stream reactor release?
Yes
### Do you have a supported version of the data source/sink .i.e Cassandra 3.0.9?
No
### Have you read the [docs](https://docs.lenses.io/connectors/)?
Yes
### What is the expected behaviour?
Moving data from kafka-topic to kudu table
### What was observed?
Error
### Please provide full log files (redact and sensitive information)
 org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:560)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: java.lang.RuntimeException: org.apache.kudu.client.NonRecoverableException: Primary key column id is not set\n\tat com.datamountaineer.streamreactor.connect.errors.ThrowErrorPolicy.handle(ErrorPolicy.scala:58)\n\tat com.datamountaineer.streamreactor.connect.errors.ErrorHandler$class.handleError(ErrorHandler.scala:83)\n\tat com.datamountaineer.streamreactor.connect.errors.ErrorHandler$class.handleTry(ErrorHandler.scala:64)\n\tat com.datamountaineer.streamreactor.connect.kudu.sink.KuduWriter.handleTry(KuduWriter.scala:50)\n\tat com.datamountaineer.streamreactor.connect.kudu.sink.KuduWriter.applyInsert(KuduWriter.scala:143)\n\tat com.datamountaineer.streamreactor.connect.kudu.sink.KuduWriter.write(KuduWriter.scala:100)\n\tat com.datamountaineer.streamreactor.connect.kudu.sink.KuduSinkTask$$anonfun$put$2.apply(KuduSinkTask.scala:68)\n\tat com.datamountaineer.streamreactor.connect.kudu.sink.KuduSinkTask$$anonfun$put$2.apply(KuduSinkTask.scala:68)\n\tat scala.Option.foreach(Option.scala:257)\n\tat com.datamountaineer.streamreactor.connect.kudu.sink.KuduSinkTask.put(KuduSinkTask.scala:68)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:538)\n\t... 10 more\nCaused by: org.apache.kudu.client.NonRecoverableException: Primary key column id is not set\n\tat org.apache.kudu.client.KuduException.transformException(KuduException.java:132)\n\tat org.apache.kudu.client.KuduSession.apply(KuduSession.java:93)\n\tat com.datamountaineer.streamreactor.connect.kudu.sink.KuduWriter$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(KuduWriter.scala:139)\n\tat com.datamountaineer.streamreactor.connect.kudu.sink.KuduWriter$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(KuduWriter.scala:139)\n\tat scala.collection.Iterator$$anon$11.next(Iterator.scala:410)\n\tat scala.collection.Iterator$GroupedIterator.takeDestructively(Iterator.scala:1074)\n\tat scala.collection.Iterator$GroupedIterator.go(Iterator.scala:1089)\n\tat scala.collection.Iterator$GroupedIterator.fill(Iterator.scala:1126)\n\tat scala.collection.Iterator$GroupedIterator.hasNext(Iterator.scala:1130)\n\tat scala.collection.Iterator$class.foreach(Iterator.scala:891)\n\tat scala.collection.AbstractIterator.foreach(Iterator.scala:1334)\n\tat com.datamountaineer.streamreactor.connect.kudu.sink.KuduWriter$$anonfun$1.apply$mcV$sp(KuduWriter.scala:141)\n\tat com.datamountaineer.streamreactor.connect.kudu.sink.KuduWriter$$anonfun$1.apply(KuduWriter.scala:141)\n\tat com.datamountaineer.streamreactor.connect.kudu.sink.KuduWriter$$anonfun$1.apply(KuduWriter.scala:141)\n\tat scala.util.Try$.apply(Try.scala:192)\n\tat com.datamountaineer.streamreactor.connect.kudu.sink.KuduWriter.applyInsert(KuduWriter.scala:136)\n\t... 16 more\nCaused by: java.lang.IllegalStateException: Primary key column id is not set\n\tat org.apache.kudu.client.KeyEncoder.encodeColumn(KeyEncoder.java:143)\n\tat org.apache.kudu.client.KeyEncoder.encodeColumns(KeyEncoder.java:126)\n\tat org.apache.kudu.client.KeyEncoder.getHashBucket(KeyEncoder.java:80)\n\tat org.apache.kudu.client.KeyEncoder.encodePartitionKey(KeyEncoder.java:96)\n\tat org.apache.kudu.client.PartitionSchema.encodePartitionKey(PartitionSchema.java:84)\n\tat org.apache.kudu.client.Operation.partitionKey(Operation.java:167)\n\tat org.apache.kudu.client.AsyncKuduClient.sendRpcToTablet(AsyncKuduClient.java:1074)\n\tat org.apache.kudu.client.AsyncKuduSession.apply(AsyncKuduSession.java:556)\n\tat org.apache.kudu.client.KuduSession.apply(KuduSession.java:79)\n\t... 30 more\n

**Comment by andrewstevenson** [comment] 2020-01-03 11:41
@mohanrajank do you have a field called id in your kafka topic?

**Comment by mohanrajank** [comment] 2020-01-03 12:49
Yes, Kafka topic sample output
  "payload": {
    "before": null,
    "after": {
      "id": 39,
      "msg": "sampletest36",
      "created_at": 1577445800487
    }

**Comment by andrewstevenson** [comment] 2020-01-03 13:01
@mohanrajank so its nested? payload.after.id

**Comment by mohanrajank** [comment] 2020-01-03 13:02
Can you please help me to fix this?

**Comment by mohanrajank** [comment] 2020-01-03 13:10
I am using the 'io.debezium.connector.sqlserver.SqlServerConnector' to move the data from ms-sql db to kafka topic and here is my sample data from kafka-console-consumer

{
  "schema": {
    "type": "struct",
    "fields": [
      {
        "type": "struct",
        "fields": [
          {
            "type": "int32",
            "optional": false,
            "field": "id"
          },
          {
            "type": "string",
            "optional": false,
            "field": "msg"
          },
          {
            "type": "int64",
            "optional": false,
            "name": "io.debezium.time.Timestamp",
            "version": 1,
            "field": "created_at"
          }
        ],
        "optional": true,
        "name": "mssql.dbo.date_test.Value",
        "field": "before"
      },
      {
        "type": "struct",
        "fields": [
          {
            "type": "int32",
            "optional": false,
            "field": "id"
          },
          {
            "type": "string",
            "optional": false,
            "field": "msg"
          },
          {
            "type": "int64",
            "optional": false,
            "name": "io.debezium.time.Timestamp",
            "version": 1,
            "field": "created_at"
          }
        ],
        "optional": true,
        "name": "mssql.dbo.date_test.Value",
        "field": "after"
      },
      {
        "type": "struct",
        "fields": [
          {
            "type": "string",
            "optional": false,
            "field": "version"
          },
          {
            "type": "string",
            "optional": false,
            "field": "connector"
          },
          {
            "type": "string",
            "optional": false,
            "field": "name"
          },
          {
            "type": "int64",
            "optional": false,
            "field": "ts_ms"
          },
          {
            "type": "string",
            "optional": true,
            "name": "io.debezium.data.Enum",
            "version": 1,
            "parameters": {
              "allowed": "true,last,false"
            },
            "default": "false",
            "field": "snapshot"
          },
          {
            "type": "string",
            "optional": false,
            "field": "db"
          },
          {
            "type": "string",
            "optional": false,
            "field": "schema"
          },
          {
            "type": "string",
            "optional": false,
            "field": "table"
          },
          {
            "type": "string",
            "optional": true,
            "field": "change_lsn"
          },
          {
            "type": "string",
            "optional": true,
            "field": "commit_lsn"
          },
          {
            "type": "int64",
            "optional": true,
            "field": "event_serial_no"
          }
        ],
        "optional": false,
        "name": "io.debezium.connector.sqlserver.Source",
        "field": "source"
      },
      {
        "type": "string",
        "optional": false,
        "field": "op"
      },
      {
        "type": "int64",
        "optional": true,
        "field": "ts_ms"
      }
    ],
    "optional": false,
    "name": "mssql.dbo.date_test.Envelope"
  },
  "payload": {
    "before": null,
    "after": {
      "id": 52,
      "msg": "sampletest07",
      "created_at": 1578076482057
    },
    "source": {
      "version": "1.0.0.Beta3",
      "connector": "sqlserver",
      "name": "mssql",
      "ts_ms": 1578076482070,
      "snapshot": "false",
      "db": "test_db",
      "schema": "dbo",
      "table": "date_test",
      "change_lsn": "000152f6:0000d41f:0003",
      "commit_lsn": "000152f6:0000d41f:0004",
      "event_serial_no": 1
    },
    "op": "c",
    "ts_ms": 1578056686155
  }
}

**Comment by mohanrajank** [comment] 2020-01-03 13:17
Hi, @andrewstevenson thanks for your reply, can you suggest a method to push this data to my kudu table using com.datamountaineer.streamreactor.connect.kudu.sink.KuduSinkConnector

**Comment by andrewstevenson** [comment] 2020-01-03 13:29
@mohanrajank you could deploy an app upstream to pull out the `after` part of the payload. https://lenses.io/ can do this for you with SQL processors. You could try also referencing the field directly but i'd have to check if the sink supports nested fields.

**Comment by mohanrajank** [comment] 2020-01-03 13:39
https://lenses.io/ support source connectors for MS-SQL DB?

**Comment by andrewstevenson** [comment] 2020-01-03 16:19
@mohanrajank we support any connector.

**Comment by mohanrajank** [comment] 2020-01-10 05:38
@andrewstevenson Hi, lenses kudu sink connector supports delete operation?

**Comment by andrewstevenson** [comment] 2020-01-10 09:44
@mohanrajank Delete is not supported, contributions welcome! If you join our slack channel you can discuss it further. I'm going to close this issue as its not a bug.

**Closed by andrewstevenson** 2020-01-10 09:44 UTC

**Comment by mohanrajank** [comment] 2020-03-11 15:26
@andrewstevenson Hi, thanks for your previous reply, I have data in my kafka topic in this form

{
"Id": 39,
"Msg": "sampletest36",
"Created_At": 1577445800487
}
with this sink config 
{
"name": "snk_test",
"config": {
"connector.class": "com.datamountaineer.streamreactor.connect.kudu.sink.KuduSinkConnector",
"topics": "mssql.dbo.date_test",
"connect.kudu.schema.registry.url": "http://localhost:8081",
"connect.kudu.master": "kudumaster:7051",
"connect.kudu.kcql": "insert into impala::default.date_test select * from mssql.dbo.date_test"
}
}

I am getting the error **'id column is not set'** I think because of **case sensitive columns** it shows this error, there is any way I can insert this data into a kudu table with lenses kudu connector?
